from abc import ABC, abstractmethod
from openai import OpenAI
import os


class BaseLlm(ABC):
    """
        Abstract Base Class (ABC) defining the required interface for a Large Language Model (LLM) service.
        This interface standardizes how the application interacts with any underlying
        model provider to generate text completions based on an input prompt.
    """
    @abstractmethod
    async def complete(self, msg: str, model: str) -> str:
        """
            Asynchronously generates a text completion from the LLM based on a prompt.
            Args:
                msg (str): The input prompt or message (including context) to send to the model.
                model (str): The name or identifier of the specific LLM to use for generation.
            Returns:
                str: The text output (completion) generated by the LLM.
        """
        pass


class OpenAiLlm(BaseLlm):
    """
        Concrete implementation of BaseLlm using the OpenAI API for text completion.
        This implementation relies on the 'openai' package and requires the
        OPENAI_API_KEY environment variable to be set for authentication.
    """
    def __init__(self):
        """
            Initializes the OpenAI client and checks for the necessary API key.
            Raises:
                EnvironmentError: If the 'OPENAI_API_KEY' environment variable is not set.
        """
        if os.environ.get("OPENAI_API_KEY") is None:
            raise EnvironmentError("OpenAI API key not set")
        print(f'api key: {os.environ.get("OPENAI_API_KEY")}')
        self._client = OpenAI()
    async def complete(self, msg: str, model: str = "gpt-5-mini") -> str:
        """
            Generates a text completion using the specified OpenAI model.
            Args:
                msg (str): The full input prompt to send to the model.
                model (str, optional): The name of the OpenAI model to use. Defaults to "gpt-5-mini".
            Returns:
                str: The generated text output, specifically the `output_text` attribute
                     of the result object.
        """
        result = self._client.responses.create(
            model=model,
            input=msg,
            reasoning={"effort": "low"},
            text={"verbosity": "low"},
        )
        return result.output_text
